### ISSUE TITLE
KeyError: 'directions'

### ISSUE THREAD

**Issue by Nuxssss** [space-wizards/RSI.py#12]
KeyError: 'directions'
Traceback (most recent call last):
  File "/home/nuxs/RSI-editor/rsi_editor/editor.py", line 286, in openRsi
    self.currentRsi = Rsi.fromFile(rsiFile)
  File "/home/nuxs/RSI-editor/rsi_editor/Rsi.py", line 34, in fromFile
    return Rsi(RSIPy.Rsi.open(rsiPath))
  File "/home/nuxs/.local/lib/python3.10/site-packages/rsi/rsi.py", line 125, in open
    state["directions"], state["name"])  # type: State

**Comment by mirrorcult** [comment]
do not use RSI-editor, that repo is archived for a reason
